spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello-mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com.hjc.demo.mappers: debug

page helper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
