version: '3.8'
name: server-compse

services:
  nodejs-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-app-image
    container_name: nodejs-service
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - "./dist:/app/dist"

