version: '3.8'

services:
  nest-app-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-app-image
    container_name: nest-app-container
    ports:
      - '3000:3000'
    volumes:
      - "./dist:/app/dist"
