# build stage
FROM node:18.0-alpine3.14 as build-stage

WORKDIR /app

COPY package.json .

RUN npm install --registry=https://registry.npmmirror.com/

COPY . .

RUN npm run build

# production stage
FROM node:18.0-alpine3.14 as production-stage

WORKDIR /app

COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/package.json .
COPY .env.prod .

RUN npm install --production --registry=https://registry.npmmirror.com/

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
