# Build stage
FROM node:20-alpine as build-stage

WORKDIR /app

COPY package.json .

RUN npm install --registry=https://registry.npmmirror.com/

COPY . .

RUN npm run build

# Production stage
FROM nginx:alpine as product-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

VOLUME /usr/share/nginx/html

EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]